// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeGZmYbvDw3SkdFsccohaD-LrVa3lSM9g',
    appId: '1:962136968511:web:9e975fdee3a0add8e3d78a',
    messagingSenderId: '962136968511',
    projectId: 'moddoapp-b34b1',
    authDomain: 'moddoapp-b34b1.firebaseapp.com',
    storageBucket: 'moddoapp-b34b1.firebasestorage.app',
    measurementId: 'G-CH9S8H6TCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr_6Do5QKfHC0Ni8yRx22tozGhC7vkqY0',
    appId: '1:962136968511:android:b2e702c17f0aa11ee3d78a',
    messagingSenderId: '962136968511',
    projectId: 'moddoapp-b34b1',
    storageBucket: 'moddoapp-b34b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrCaakHfQ1cOQfElASG7plYUDpl1M8UAQ',
    appId: '1:962136968511:ios:f25b00b7691a8f58e3d78a',
    messagingSenderId: '962136968511',
    projectId: 'moddoapp-b34b1',
    storageBucket: 'moddoapp-b34b1.firebasestorage.app',
    iosBundleId: 'com.example.moodoApp',
  );
}
